# Generated by Django 3.0.7 on 2020-06-16 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='urlsavemodel',
            old_name='url_path',
            new_name='the_url',
        ),
    ]
