# Generated by Django 3.0.7 on 2020-06-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0002_auto_20200616_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsavemodel',
            name='the_url',
            field=models.URLField(max_length=256),
        ),
    ]
