# Generated by Django 3.0.7 on 2020-06-18 13:02

from django.db import migrations
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0003_auto_20200617_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urlsavemodel',
            name='the_url',
            field=embed_video.fields.EmbedVideoField(),
        ),
    ]
