# Generated by Django 3.0.7 on 2020-07-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlapp', '0006_auto_20200702_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprof',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
